import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono NFM"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
opacity = 0.97
blur = true

[window.padding]
x = 10
y = 10

[cursor]
style = "Block"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

